resolver = "2"

[workspace]
members = [
  "derive",
  "parser",
  "examples"
]

[workspace.dependencies]
regex = "1.5.5"
minify-html = "0.15.0"

[package]
name = "rusty-handlebars"
version = "0.1.6"
edition = "2021"

[dependencies]
rusty-handlebars-derive = { path = "derive", version = "0.1.6"}
rusty-handlebars-parser = { path = "parser", version = "0.1.6", optional = true }

[features]
parser = ["dep:rusty-handlebars-parser"]