[workspace]
members = [
  "derive",
  "parser",
  "examples",
  "language-server"
]

[workspace.package]
authors = ["Jerome Johnson <nosnhoj.emorej@gmail.com>"]
license = "MIT"
repository = "https://github.com/h-i-v-e/rusty-handlebars"

[workspace.dependencies]
minify-html = "0.18.1"

[package]
name = "rusty-handlebars"
version = "0.3.0"
edition = "2021"
description = "Compile Handlebars-like templates into Rust Display implementations"
authors.workspace = true
repository.workspace = true
license-file = "LICENSE.txt"
keywords = ["handlebars", "template", "engine"]
categories = ["template-engine", "compilers"]

[dependencies]
rusty-handlebars-derive = { path = "derive", version = "0.3.0", default-features = false }
rusty-handlebars-parser = { path = "parser", version = "0.3.0", optional = true, default-features = false }

[features]
default = ["minify-html"]
parser = ["dep:rusty-handlebars-parser"]
minify-html = [
  "rusty-handlebars-derive/minify-html",
  "rusty-handlebars-parser?/minify-html"
]
