[package]
name = "rusty-handlebars-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.15"
regex.workspace = true
rusty-handlebars-parser = {path = "../parser"}
syn = {version = "^2.0.0", features = ["full"]}