[package]
name = "rusty-handlebars-language-server"
version = "0.2.0"
edition = "2021"
description = "Language Server Protocol support for Rusty Handlebars templates"
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
cargo_metadata = "0.23.1"
lsp-server = "0.10.0"
lsp-types = "0.97.0"
rusty-handlebars-parser = { path = "../parser", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = { version = "3.0.3", features = ["full"] }

[dev-dependencies]
tempfile = "3"
