[package]
name = "rusty-handlebars-examples"
version = "0.1.7"
edition = "2021"

[dependencies]
serde_json = "^1.0.122"
rusty-handlebars = { path = "../", features = ["derive", "parser"] }

[build-dependencies]
rusty-handlebars = { path = "../", features = ["derive", "parser", "minify-html"] }