[package]
name = "rusty-handlebars-parser"
version = "0.1.7"
edition = "2021"

[dependencies]
regex.workspace = true
minify-html = {workspace = true, optional = true}

[features]
minify-html = ["dep:minify-html"]
default = ["minify-html"]