[package]
name = "rusty-handlebars-parser"
version = "0.1.4"
edition = "2021"
description = "Rust source generator for rusty-handlebars templates"
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["handlebars", "template", "engine"]
categories = ["template-engine", "compilers"]

[dependencies]
minify-html = {workspace = true, optional = true}

[features]
minify-html = ["dep:minify-html"]
default = ["minify-html"]
